language: swift
osx_image: xcode9.2

cache: cocoapods
podfile: Example/Podfile

before_install:
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild -workspace Example/collection-view-layouts.xcworkspace -scheme collection-view-layouts-Example -configuration 'Debug' -sdk 'iphonesimulator11.2' -destination 'platform=iOS Simulator,name=iPhone 7' test | xcpretty -f `xcpretty-travis-formatter`
- pod lib lint