language: swift
osx_image: xcode9.2

cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods -v '1.7.1'
- pod repo update
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild -workspace Example/collection-view-layouts.xcworkspace -scheme collection-view-layouts-Example -configuration 'Debug' -sdk 'iphonesimulator11.2' -destination 'platform=iOS Simulator,name=iPhone 7' test | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bash <(curl -s https://codecov.io/bash)