language: swift
osx_image: xcode9.2

cache: cocoapods
podfile: Example/Podfile

before_install:
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/collection-view-layouts.xcworkspace -scheme collection-view-layouts_Example -sdk iphonesimulator11.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint