language: swift
osx_image: xcode9.2

cache: cocoapods
podfile: Example/Podfile

before_install:
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/${POD_NAME}.xcworkspace -scheme ${POD_NAME}-Example -sdk iphonesimulator11.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
